name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (use the latest version of Node)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # you can specify your desired version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the app
      - name: Build the app
        run: npm run build

      - name: Set up Git user for commits
        run: |
          git config --global user.name "hesan21"
          git config --global user.email "hesannaveed21@gmail.com"

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
